# version: '3.8'
services:
  backend:
    build:
      context: ./doadornet-be
    image: doadornet-backend
    container_name: doadornet-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/doadornet
      - SPRING_DATASOURCE_USERNAME=doadornet
      - SPRING_DATASOURCE_PASSWORD=doadornet
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: doadornet-mysql
    environment:
      MYSQL_ROOT_PASSWORD: doadornet
      MYSQL_DATABASE: doadornet
      MYSQL_USER: doadornet
      MYSQL_PASSWORD: doadornet
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
